name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:

env:
  GO_VERSION: "1.20"
  NODE_VERSION: "18"
  JAVA_VERSION: "17"
  ANT_VERSION: "1.10.13"
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"

jobs:
  build:
    uses: portapps/.github/.github/workflows/app-build.yml@master
